fixtures:
  symlinks:
    profile: "#{source_dir}/site/profile"
    role: "#{source_dir}/site/role"
  repositories:
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive'
      ref:  '3.2.0'
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt'
      ref:  '4.5.0'
    chocolatey:
      repo: 'https://github.com/puppetlabs/puppetlabs-chocolatey'
      ref:  '3.0.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat'
      ref:  '4.1.1'
    docker:
      repo: 'https://github.com/puppetlabs/puppetlabs-docker'
      ref:  '2.0.0'
    dsc:
      repo: 'https://github.com/puppetlabs/puppetlabs-dsc'
      ref:  '1.4.1'
    epel:
      repo: 'https://github.com/stahnma/puppet-module-epel'
      ref:  '1.3.1'
    grafana:
      repo: 'https://github.com/voxpupuli/puppet-grafana'
      ref:  'v4.0.3'
    graphite:
      repo: 'https://github.com/echocat/puppet-graphite'
      ref:  'v7.2.0'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile'
      ref:  '2.3.0'
    java:
      repo: 'https://github.com/puppetlabs/puppetlabs-java'
      ref:  '3.0.0'
    jenkins:
      repo: 'https://github.com/voxpupuli/puppet-jenkins'
      ref:  'v1.7.0'
    node_encrypt:
      repo: 'https://github.com/binford2k/binford2k-node_encrypt'
      ref:  'v0.3.3'
    nservicebusservicecontrol:
      repo: 'https://github.com/TraGicCode/tragiccode-nservicebusservicecontrol'
      branch: 'master'
    powershell:
      repo: 'https://github.com/puppetlabs/puppetlabs-powershell'
      ref:  '2.1.3'
    rabbitmq:
      repo: 'https://github.com/voxpupuli/puppet-rabbitmq'
      ref:  'v8.1.0'
    ravendb: 
      repo: 'https://github.com/tragiccode/tragiccode-ravendb'
      ref:  'v0.4.0'
    rbac:
      repo: 'https://github.com/puppetlabs/pltraining-rbac'
      ref:  'v0.0.7'
    reboot:
      repo: 'https://github.com/puppetlabs/puppetlabs-reboot'
      ref:  '2.0.0'
    redis:
      repo: 'https://github.com/arioch/puppet-redis'
      ref:  'v3.3.0'
    registry:
      repo: 'https://github.com/puppetlabs/puppetlabs-registry'
      ref:  '2.0.2'
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby'
      ref:  '1.0.0'
    rvm:
      repo: 'https://github.com/maestrodev/puppet-rvm'
      ref:  'v1.13.1'
    splunk:
      repo: 'https://github.com/voxpupuli/puppet-splunk'
      ref:  'v7.1.0'
    squid:
      repo: 'https://github.com/voxpupuli/puppet-squid'
      ref:  'v0.5.0'
    staging:
      repo: 'https://github.com/voxpupuli/puppet-staging'
      ref:  'v3.2.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
      ref:  '4.24.0'
    vault:
      repo: 'https://github.com/jsok/puppet-vault'
      ref:  'v1.2.8'
    wget:
      repo: 'https://github.com/maestrodev/puppet-wget'
      ref:  'v1.7.3'
    wsus_client:
      repo: 'https://github.com/puppetlabs/puppetlabs-wsus_client'
      ref:  '1.0.3'